parameters:
- name: 'STORAGE_ACCOUNT_NAME'
  type: string
  default: 'rg-asgrndv3-main-rndv3-eastus2-003'
- name: 'RESOURCE_GROUP'
  type: string
  default: 'rg-asgrndv3-main-rndv3-eastus2-003'
- name: 'AZURE_SERVICE_CONNECTION'
  type: string
  default: 'asgrndv3-test-storage-account'

jobs:
  - job: install_azure_cli
    displayName: Install Azure CLI
    steps:
    - script: |
        set -e
        if ! which az &> /dev/null; then
          curl -Ls -o azure-cli_bionic_all.deb https://aka.ms/InstallAzureCliBionicEdge && sudo dpkg -i azure-cli_bionic_all.deb
        fi
  - job: file_share_backup
    displayName: File share on-demand backup
    steps: 
    - task: AzureCLI@2
      displayName: 'Azure CLI: Backup file share'
      inputs:
        scriptType: bash
        azureSubscription: ${{parameters.AZURE_SERVICE_CONNECTION}}
        scriptLocation: inlineScript
        inlineScript: |
          az storage account show -g MyResourceGroup -n MyStorageAccount